all:
  hosts:
    server1:
      ansible_connection: ssh
      ansible_host: "103.134.154.200"
      ansible_port: 22
      ansible_user: "polindra"
      ansible_password: "Polindra123"
      ansible_private_key_file: "C:\\Users\\Rida Nurul Afifah\\.ssh\\id_rsa"
